package com.drox7.myapplication.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF3699E7)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF6FF7F5)
val md_theme_light_onPrimaryContainer = Color(0xFF00201F)
val md_theme_light_secondary = Color(0xFF4A6362)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCCE8E7)
val md_theme_light_onSecondaryContainer = Color(0xFF051F1F)
val md_theme_light_tertiary = Color(0xFF4B607C)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD2E4FF)
val md_theme_light_onTertiaryContainer = Color(0xFF031C35)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFEBEEF3)
val md_theme_light_onBackground = Color(0xFF191C1C)
val md_theme_light_surface = Color(0xFFFAFDFC)
val md_theme_light_onSurface = Color(0xFF191C1C)
val md_theme_light_surfaceVariant = Color(0xFFF4F7F6)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4948)
val md_theme_light_outline = Color(0xFF796F75)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1F0)
val md_theme_light_inverseSurface = Color(0xFF2D3131)
val md_theme_light_inversePrimary = Color(0xFF4DDAD8)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006A69)
val md_theme_light_outlineVariant = Color(0xFFBEC9C8)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF3699E7)
val md_theme_dark_onPrimary = Color(0xFF1A1A1A)
val md_theme_dark_primaryContainer = Color(0xFF00504F)
val md_theme_dark_onPrimaryContainer = Color(0xFF6FF7F5)
val md_theme_dark_secondary = Color(0xFFB0CCCB)
val md_theme_dark_onSecondary = Color(0xFF1B3534)
val md_theme_dark_secondaryContainer = Color(0xFF324B4A)
val md_theme_dark_onSecondaryContainer = Color(0xFFCCE8E7)
val md_theme_dark_tertiary = Color(0xFFB2C8E8)
val md_theme_dark_onTertiary = Color(0xFF1B324B)
val md_theme_dark_tertiaryContainer = Color(0xFF334863)
val md_theme_dark_onTertiaryContainer = Color(0xFFD2E4FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF000000)
val md_theme_dark_onBackground = Color(0xFFE0E3E2)
val md_theme_dark_surface = Color(0xFF191C1C)
val md_theme_dark_onSurface = Color(0xFFE0E3E2)
val md_theme_dark_surfaceVariant = Color(0xFF3F4948)
val md_theme_dark_onSurfaceVariant = Color(0xFFBEC9C8)
val md_theme_dark_outline = Color(0xFF889392)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1C)
val md_theme_dark_inverseSurface = Color(0xFFE0E3E2)
val md_theme_dark_inversePrimary = Color(0xFF006A69)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF4DDAD8)
val md_theme_dark_outlineVariant = Color(0xFF3F4948)
val md_theme_dark_scrim = Color(0xFF000000)

//My Colors
val Red = Color(0x80D32F2F)
val YellowLight = Color(0xB3FFB74D)
val GreenLight = Color(0xB3388E3C)
val Pink40 = Color(0xFF7D5260)
val BlueLight = Color(0xFF3699E7)
val BlueLightSum = Color(0xB23699E7)
val GrayLight = Color(0xFFA2A0A0)
val DarkText = Color(0xFF242424)
val LightText = Color(0xFF5C5B5B)

val seed = Color(0xFF006A69)
